### ISSUE TITLE
Question regarding the extracted poses

### ISSUE THREAD

**Issue by YuDeng** [JeffWang987/EgoVid#2]
Hi, thanks for releasing this excellent dataset!

I have two questions regarding the processed data:
1. I've downloaded the dataset from [modelscope](https://modelscope.cn/datasets/iic/EgoVid/summary) and unzipped all poses. However, I found that the length of the pose labels is different from that of the video clips. I believe the video length is calculated by end_frame-start_frame, which turns to be around 160, while the length of the poses are always 120. What's the correspondence between the poses and the video frames?

2. I only found labels for around 68K video clips, while the claimed total number in the paper is 5M. Is the released data only a part of the whole dataset?

Looking forward to your reply.

**Comment by JeffWang987** [comment]
We appreciate your interest in EgoVid and are sorry for the misunderstanding.
1. The length of poses is indeed 120 frames. Namely, the corresponding video index is [start_frame, start_frame+120]. The end_frame is for the text-control tasks. For pose-guided tasks, you can omit the end_frame.
2. Due to [Known Issues](https://ego4d-data.org/docs/data/imu/) in the original IMU annotation, we only select 68K videos suitable for pose calculation, as indicated in our paper (Sec 5.1). The 5M data is for text action annotation and cleaning metadata.

**Comment by YuDeng** [comment]
Thanks for your quick response. This solves my issue.

**Comment by YuDeng** [comment]
By the way, I have another issue regarding the estimated intrinsics. It seems that the camera model is treated as a pinhole camera without fisheye distortion. However, in the Ego4D dataset, some videos have large nonlinear distortions. How accurate is the estimated pose for these cases under a pinhole camera assumption?

**Comment by JeffWang987** [comment]
Thank you for your suggestions! Over the past few days, we’ve been discussing related issues with the community. The current version only utilizes the pinhole camera model without distortion. We plan to continuously update the annotations  and warmly welcome the community to contribute updates as well!
